### PR TITLE
Alexa v3

### PR DESCRIPTION
**Pull request by mike-grant**

### CODE REVIEW

**Comment by cbrherms** [comment]
Was there something up with the code? Or was it accidentally closed due to you pulling from your v3 branch rather than your master which you'd merged it in to?

**Comment by mike-grant** [comment]
I accidentally picked the wrong branch for merging. I meant to merge from v3 into my master, but selected the wrong branch as the target!

**Comment by cbrherms** [comment]
Ahhh I see. Well, glad someone is working on rewriting the code for v3. Looking at the date of last commit I'm assuming @auchter may be dropping support for haaska with cloud coming out. 
Seeing as that's only available in the US your fork will be an interesting one to watch.

**Comment by trisk** [comment]
Have you looked at the video-skill branch (which also implemented v3 discovery but wasn't working reliably since the v3 interface was undocumented at the time) to see if there's anything useful there?

**Pull request closed without merging**
