### PR TITLE
Add color temp decrement increment

### PR DESCRIPTION
**Pull request by keatontaylor**
This allows alexa to increment and decrement light color according to
the smart home skill api.

### CODE REVIEW

**Comment by auchter** [comment]
Looks good to me, but for some reason I'm having difficulty actually invoking it via my Echo. Setting the color temperature directly works fine, but asking to make a light warmer/cooler whiter/softer either just responds with a "ding" or "I don't know how to set corner light to that setting", without the request ever hitting haaska.

No idea what's going on there. I'll still merge this and assume there's something weird on my end.

**Comment by keatontaylor** [comment]
@auchter, since discovery is what provides the list of actions that the device can respond to, I had to forget then rediscover all my devices before it would properly work.

**Comment by auchter** [comment]
Yeah, I tried that to no avail.

**Comment by keatontaylor** [comment]
Interesting, the voice commands that work for me are:

Alexa, make <name of light/group> warmer/cooler.

However, if I say:

Alexa, set <name of light/group> warmer/cooler. I get the same error response as you.

**Comment by keatontaylor** [comment]
Any reason this was closed vs. merged?

**Comment by auchter** [comment]
Sorry about that. I pulled your commit and merged it via the command line, and closed the pull request prior to pushing to Github. Your commit was merged, but I'm not sure how to reconcile this so it actually shows as "Merged"` I even tried amending the commit message to add "Closes #56" in the hopes that Github would pick up on it, but that didn't seem to work.

**Comment by keatontaylor** [comment]
Works for me, I just hadn't realized the changes made it to master.

**Pull request closed without merging**
